version: "3"

services:
  auth:
    build:
      context: ./services/auth/
    restart: always
    env_file:
      - .env
    environment:
      - API_SECRET=$API_SECRET
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - "8080:8080"
    # volumes:
    #   - ./:/app
    depends_on:
      - "db"

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - ./databases/auth/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
volumes:
  db-data:
